"""Main UI project & Timmer."""

#PyQT5

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QSystemTrayIcon, QApplication

#CEToolkit
from func import stopwatchfunc
from func import segmentationfunc
from func import designfunc
from func import reportfunc
from func import kpifunc

#Python
import sys
import os

#Parent relationship
stopwatchfunc.parent = sys.modules[__name__]
segmentationfunc.parent = sys.modules[__name__]
designfunc.parent = sys.modules[__name__]
reportfunc.parent = sys.modules[__name__]
kpifunc.parent = sys.modules[__name__]

#Global variables
#StopWatch
secondLCD = "00"
minuteLCD = "00"
hourLCD = "00"
second = 0
minute = 0
hour = 0

#Segmentation Tab
contador_framework_orthognatic = 0 
band_framework_button = 0

#Design Tab
band_wraps_button = 0
contador_wraps = 0

#Report tab
band_teeth_button = 0
contador_report = 0

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        """location and definitions elements in the UI"""

        #Main widget
        MainWidget.setObjectName("MainWidget")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWidget.sizePolicy().hasHeightForWidth())
        MainWidget.setSizePolicy(sizePolicy)
        MainWidget.setMinimumSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWidget.setFont(font)
        MainWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWidget.setFixedSize(1074, 710)
        
        #Tab STOPWATCH
        self.tab_stopwatch = QtWidgets.QWidget()
        self.tab_stopwatch.setObjectName("tab_stopwatch")
        self.label_stopwatch_title_stopwatch = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_title_stopwatch.setGeometry(QtCore.QRect(100, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(38)
        self.label_stopwatch_title_stopwatch.setFont(font)
        self.label_stopwatch_title_stopwatch.setObjectName("label_stopwatch_title_stopwatch")
        self.lineEdit_stopwatch_hour = QtWidgets.QLineEdit(self.tab_stopwatch)
        self.lineEdit_stopwatch_hour.setGeometry(QtCore.QRect(70, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_stopwatch_hour.setFont(font)
        self.lineEdit_stopwatch_hour.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_stopwatch_hour.setObjectName("lineEdit_stopwatch_hour")
        self.lineEdit_stopwatch_minutes = QtWidgets.QLineEdit(self.tab_stopwatch)
        self.lineEdit_stopwatch_minutes.setGeometry(QtCore.QRect(200, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_stopwatch_minutes.setFont(font)
        self.lineEdit_stopwatch_minutes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_stopwatch_minutes.setObjectName("lineEdit_stopwatch_minutes")
        self.lineEdit_stopwatch_seconds = QtWidgets.QLineEdit(self.tab_stopwatch)
        self.lineEdit_stopwatch_seconds.setGeometry(QtCore.QRect(320, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_stopwatch_seconds.setFont(font)
        self.lineEdit_stopwatch_seconds.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_stopwatch_seconds.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_stopwatch_seconds.setObjectName("lineEdit_stopwatch_seconds")
        self.label_stopwatch_dot = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_dot.setGeometry(QtCore.QRect(160, 160, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_stopwatch_dot.setFont(font)
        self.label_stopwatch_dot.setObjectName("label_stopwatch_dot")
        self.label_stopwatch_dot_2 = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_dot_2.setGeometry(QtCore.QRect(280, 160, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_stopwatch_dot_2.setFont(font)
        self.label_stopwatch_dot_2.setObjectName("label_stopwatch_dot_2")
        self.lcdNumber_stopwatch = QtWidgets.QLCDNumber(self.tab_stopwatch)
        self.lcdNumber_stopwatch.setGeometry(QtCore.QRect(50, 230, 341, 161))
        self.lcdNumber_stopwatch.setSmallDecimalPoint(False)
        self.lcdNumber_stopwatch.setDigitCount(8)
        self.lcdNumber_stopwatch.setMode(QtWidgets.QLCDNumber.Hex)
        self.lcdNumber_stopwatch.setProperty("intValue", 0)
        self.lcdNumber_stopwatch.display("00:00:00") #A
        self.lcdNumber_stopwatch.setObjectName("lcdNumber_stopwatch")
        self.pushButton_stopwatch_reset = QtWidgets.QPushButton(self.tab_stopwatch)
        self.pushButton_stopwatch_reset.setGeometry(QtCore.QRect(50, 410, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stopwatch_reset.setFont(font)
        self.pushButton_stopwatch_reset.setObjectName("pushButton_stopwatch_reset")
        self.pushButton_stopwatch_stop_up = QtWidgets.QPushButton(self.tab_stopwatch)
        self.pushButton_stopwatch_stop_up.setGeometry(QtCore.QRect(170, 410, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stopwatch_stop_up.setFont(font)
        self.pushButton_stopwatch_stop_up.setObjectName("pushButton_stopwatch_stop_up")
        self.pushButton_stopwatch_start_up = QtWidgets.QPushButton(self.tab_stopwatch)
        self.pushButton_stopwatch_start_up.setGeometry(QtCore.QRect(290, 410, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stopwatch_start_up.setFont(font)
        self.pushButton_stopwatch_start_up.setObjectName("pushButton_stopwatch_start_up")
        self.pushButton_stopwatch_start_down = QtWidgets.QPushButton(self.tab_stopwatch)
        self.pushButton_stopwatch_start_down.setGeometry(QtCore.QRect(290, 470, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stopwatch_start_down.setFont(font)
        self.pushButton_stopwatch_start_down.setObjectName("pushButton_stopwatch_start_down")
        self.line = QtWidgets.QFrame(self.tab_stopwatch)
        self.line.setGeometry(QtCore.QRect(490, 0, 16, 681))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_stopwatch_targets = QtWidgets.QComboBox(self.tab_stopwatch)
        self.comboBox_stopwatch_targets.setGeometry(QtCore.QRect(100, 140, 261, 31))
        self.comboBox_stopwatch_targets.setObjectName("comboBox_stopwatch_targets")
        self.comboBox_stopwatch_targets.addItem("")
        self.comboBox_stopwatch_targets.addItem("")
        self.comboBox_stopwatch_targets.addItem("")
        self.comboBox_stopwatch_targets.addItem("")
        self.comboBox_stopwatch_targets.addItem("")
        self.comboBox_stopwatch_targets.addItem("")
        self.comboBox_stopwatch_targets.addItem("")
        self.label_stopwatch_title_calculator = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_title_calculator.setGeometry(QtCore.QRect(580, 50, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(38)
        self.label_stopwatch_title_calculator.setFont(font)
        self.label_stopwatch_title_calculator.setObjectName("label_stopwatch_title_calculator")
        self.label_stopwatch_start = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_start.setGeometry(QtCore.QRect(660, 200, 47, 13))
        self.label_stopwatch_start.setObjectName("label_stopwatch_start")
        self.label_stopwatch_end = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_end.setGeometry(QtCore.QRect(660, 250, 47, 13))
        self.label_stopwatch_end.setObjectName("label_stopwatch_end")
        self.dateTimeEdit_stopwatch_end = QtWidgets.QDateTimeEdit(self.tab_stopwatch)
        self.dateTimeEdit_stopwatch_end.setGeometry(QtCore.QRect(730, 240, 101, 31))
        self.dateTimeEdit_stopwatch_end.setFrame(True)
        self.dateTimeEdit_stopwatch_end.setSpecialValueText("")
        self.dateTimeEdit_stopwatch_end.setDate(QtCore.QDate(2000, 1, 1))
        self.dateTimeEdit_stopwatch_end.setCalendarPopup(False)
        self.dateTimeEdit_stopwatch_end.setObjectName("dateTimeEdit_stopwatch_end")
        self.dateTimeEdit_stopwatch_start = QtWidgets.QDateTimeEdit(self.tab_stopwatch)
        self.dateTimeEdit_stopwatch_start.setGeometry(QtCore.QRect(730, 190, 101, 31))
        self.dateTimeEdit_stopwatch_start.setFrame(True)
        self.dateTimeEdit_stopwatch_start.setSpecialValueText("")
        self.dateTimeEdit_stopwatch_start.setDate(QtCore.QDate(2000, 1, 3))
        self.dateTimeEdit_stopwatch_start.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_stopwatch_start.setCalendarPopup(False)
        self.dateTimeEdit_stopwatch_start.setObjectName("dateTimeEdit_stopwatch_start")
        self.label_stopwatch_adjustment = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_adjustment.setGeometry(QtCore.QRect(630, 300, 101, 20))
        self.label_stopwatch_adjustment.setObjectName("label_stopwatch_adjustment")
        self.lineEdit_stopwatch_total = QtWidgets.QLineEdit(self.tab_stopwatch)
        self.lineEdit_stopwatch_total.setGeometry(QtCore.QRect(730, 340, 101, 31))
        self.lineEdit_stopwatch_total.setObjectName("lineEdit_stopwatch_total")
        self.label_stopwatch_total = QtWidgets.QLabel(self.tab_stopwatch)
        self.label_stopwatch_total.setGeometry(QtCore.QRect(650, 350, 51, 20))
        self.label_stopwatch_total.setObjectName("label_stopwatch_total")
        self.lineEdit_stopwatch_adjustment = QtWidgets.QLineEdit(self.tab_stopwatch)
        self.lineEdit_stopwatch_adjustment.setGeometry(QtCore.QRect(730, 290, 101, 31))
        self.lineEdit_stopwatch_adjustment.setObjectName("lineEdit_stopwatch_adjustment")
        self.lineEdit_stopwatch_adjustment.setText("0")
        self.pushButton_stopwatch_calculate = QtWidgets.QPushButton(self.tab_stopwatch)
        self.pushButton_stopwatch_calculate.setGeometry(QtCore.QRect(730, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stopwatch_calculate.setFont(font)
        self.pushButton_stopwatch_calculate.setObjectName("pushButton_stopwatch_calculate")
        MainWidget.addTab(self.tab_stopwatch, "")

        #Tab SEGMENTATION#
        self.tab_segmentation = QtWidgets.QWidget()
        self.tab_segmentation.setObjectName("tab_segmentation")
        self.comboBox_segmentation_surgery = QtWidgets.QComboBox(self.tab_segmentation)
        self.comboBox_segmentation_surgery.setGeometry(QtCore.QRect(90, 50, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_segmentation_surgery.setFont(font)
        self.comboBox_segmentation_surgery.setObjectName("comboBox_segmentation_surgery")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.comboBox_segmentation_surgery.addItem("")
        self.pushButton_segmentation_back = QtWidgets.QPushButton(self.tab_segmentation)
        self.pushButton_segmentation_back.setGeometry(QtCore.QRect(450, 620, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_segmentation_back.setFont(font)
        self.pushButton_segmentation_back.setObjectName("pushButton_segmentation_back")
        self.pushButton_segmentation_next = QtWidgets.QPushButton(self.tab_segmentation)
        self.pushButton_segmentation_next.setGeometry(QtCore.QRect(900, 620, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_segmentation_next.setFont(font)
        self.pushButton_segmentation_next.setObjectName("pushButton_segmentation_next")
        self.textEdit_segmentation_image = QtWidgets.QTextEdit(self.tab_segmentation)
        self.textEdit_segmentation_image.setGeometry(QtCore.QRect(450, 50, 550, 550))
        self.textEdit_segmentation_image.setObjectName("textEdit_segmentation_image")
        self.textEdit_segmentation_image.setReadOnly(True)
        self.label_segmentation_image = QtWidgets.QLabel(self.tab_segmentation)
        self.label_segmentation_image.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_segmentation_image.setText("")
        self.label_segmentation_image.setScaledContents(True)
        self.label_segmentation_image.setObjectName("label_segmentation_image")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_segmentation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 120, 211, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_segmentation = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_segmentation.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_segmentation.setObjectName("verticalLayout_segmentation")
        self.pushButton_segmentation_names = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_segmentation_names.setObjectName("pushButton_segmentation_names")
        self.verticalLayout_segmentation.addWidget(self.pushButton_segmentation_names)
        self.pushButton_segmentation_framework = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_segmentation_framework.setObjectName("pushButton_segmentation_framework")
        self.verticalLayout_segmentation.addWidget(self.pushButton_segmentation_framework)
        self.pushButton_segmentation_objects = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_segmentation_objects.setObjectName("pushButton_segmentation_objects")
        self.verticalLayout_segmentation.addWidget(self.pushButton_segmentation_objects)
        self.pushButton_segmentation_preplanfolders = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_segmentation_preplanfolders.setObjectName("pushButton_segmentation_preplanfolders")
        self.verticalLayout_segmentation.addWidget(self.pushButton_segmentation_preplanfolders)
        self.pushButton_segmentation_preplancuts = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_segmentation_preplancuts.setObjectName("pushButton_segmentation_preplancuts")
        self.verticalLayout_segmentation.addWidget(self.pushButton_segmentation_preplancuts)
        MainWidget.addTab(self.tab_segmentation, "")

        #Tab Design#
        self.tab_design = QtWidgets.QWidget()
        self.tab_design.setObjectName("tab_design")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_design_image = QtWidgets.QTextEdit(self.tab_design)
        self.textEdit_design_image.setGeometry(QtCore.QRect(450, 50, 550, 550))
        self.textEdit_design_image.setObjectName("textEdit_design_image")
        self.textEdit_design_image.setReadOnly(True)
        self.pushButton_design_next = QtWidgets.QPushButton(self.tab_design)
        self.pushButton_design_next.setGeometry(QtCore.QRect(900, 620, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_design_next.setFont(font)
        self.pushButton_design_next.setObjectName("pushButton_design_next")
        self.pushButton_design_back = QtWidgets.QPushButton(self.tab_design)
        self.pushButton_design_back.setGeometry(QtCore.QRect(450, 620, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_design_back.setFont(font)
        self.pushButton_design_back.setObjectName("pushButton_design_back")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_design)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 120, 211, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_design = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_design.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_design.setObjectName("verticalLayout_design")
        self.pushButton_design_rnames = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_rnames.setObjectName("pushButton_design_rnames")
        self.verticalLayout_design.addWidget(self.pushButton_design_rnames)
        self.pushButton_design_pnames = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_pnames.setObjectName("pushButton_design_pnames")
        self.verticalLayout_design.addWidget(self.pushButton_design_pnames)
        self.pushButton_design_parameters = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_parameters.setObjectName("pushButton_design_parameters")
        self.verticalLayout_design.addWidget(self.pushButton_design_parameters)
        self.pushButton_design_wraps = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_wraps.setObjectName("pushButton_design_wraps")
        self.verticalLayout_design.addWidget(self.pushButton_design_wraps)
        self.pushButton_design_folder = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_folder.setObjectName("pushButton_design_folder")
        self.verticalLayout_design.addWidget(self.pushButton_design_folder)
        self.pushButton_design_ceph = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_ceph.setObjectName("pushButton_design_ceph")
        self.verticalLayout_design.addWidget(self.pushButton_design_ceph)
        self.pushButton_design_flags = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_design_flags.setObjectName("pushButton_design_flags")
        self.verticalLayout_design.addWidget(self.pushButton_design_flags)
        self.label_design_image = QtWidgets.QLabel(self.tab_design)
        self.label_design_image.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_design_image.setText("")
        self.label_design_image.setScaledContents(True)
        self.label_design_image.setObjectName("label_design_image")
        MainWidget.addTab(self.tab_design, "")

        #TAB Report#
        self.tab_report = QtWidgets.QWidget()
        self.tab_report.setObjectName("tab_report")
        self.textEdit_report_image = QtWidgets.QTextEdit(self.tab_report)
        self.textEdit_report_image.setGeometry(QtCore.QRect(450, 50, 550, 550))
        self.textEdit_report_image.setObjectName("textEdit_report_image")
        self.textEdit_report_image.setReadOnly(True)
        self.pushButton_report_next = QtWidgets.QPushButton(self.tab_report)
        self.pushButton_report_next.setGeometry(QtCore.QRect(900, 620, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_report_next.setFont(font)
        self.pushButton_report_next.setObjectName("pushButton_report_next")
        self.pushButton_report_back = QtWidgets.QPushButton(self.tab_report)
        self.pushButton_report_back.setGeometry(QtCore.QRect(450, 620, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_report_back.setFont(font)
        self.pushButton_report_back.setObjectName("pushButton_report_back")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_report)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 130, 211, 200))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_report_comments = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_report_comments.setObjectName("pushButton_report_comments")
        self.verticalLayout_4.addWidget(self.pushButton_report_comments)
        self.pushButton_report_parameters = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_report_parameters.setObjectName("pushButton_report_parameters")
        self.verticalLayout_4.addWidget(self.pushButton_report_parameters)
        self.pushButton_report_teeth = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_report_teeth.setObjectName("pushButton_report_teeth")
        self.verticalLayout_4.addWidget(self.pushButton_report_teeth)
        self.pushButton_report_colors = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_report_colors.setObjectName("pushButton_report_colors")
        self.verticalLayout_4.addWidget(self.pushButton_report_colors)
        self.pushButton_report_ART = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_report_ART.setObjectName("pushButton_report_ART")
        self.verticalLayout_4.addWidget(self.pushButton_report_ART)
        self.label_report_image = QtWidgets.QLabel(self.tab_report)
        self.label_report_image.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_report_image.setText("")
        self.label_report_image.setScaledContents(True)
        self.label_report_image.setObjectName("label_report_image")
        MainWidget.addTab(self.tab_report, "")

        #TAB KPI#
        self.tab_kpi = QtWidgets.QWidget()
        self.tab_kpi.setObjectName("tab_kpi")
        self.lineEdit_kpi_caseid = QtWidgets.QLineEdit(self.tab_kpi)
        self.lineEdit_kpi_caseid.setGeometry(QtCore.QRect(110, 160, 231, 31))
        self.lineEdit_kpi_caseid.setText("")
        self.lineEdit_kpi_caseid.setObjectName("lineEdit_kpi_caseid")
        self.lineEdit_kpi_time = QtWidgets.QLineEdit(self.tab_kpi)
        self.lineEdit_kpi_time.setGeometry(QtCore.QRect(110, 380, 91, 31))
        self.lineEdit_kpi_time.setObjectName("lineEdit_kpi_time")
        self.comboBox_kpi_surgery = QtWidgets.QComboBox(self.tab_kpi)
        self.comboBox_kpi_surgery.setGeometry(QtCore.QRect(110, 230, 200, 31))
        self.comboBox_kpi_surgery.setObjectName("comboBox_kpi_surgery")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_surgery.addItem("")
        self.comboBox_kpi_rev = QtWidgets.QComboBox(self.tab_kpi)
        self.comboBox_kpi_rev.setGeometry(QtCore.QRect(200, 340, 61, 21))
        self.comboBox_kpi_rev.setObjectName("comboBox_kpi_rev")
        self.comboBox_kpi_rev.addItem("")
        self.comboBox_kpi_rev.addItem("")
        self.comboBox_kpi_rev.addItem("")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_kpi_register = QtWidgets.QPushButton(self.tab_kpi)
        self.pushButton_kpi_register.setGeometry(QtCore.QRect(170, 610, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_kpi_register.setFont(font)
        self.pushButton_kpi_register.setObjectName("pushButton_kpi_register")
        self.label_kpi_surgery = QtWidgets.QLabel(self.tab_kpi)
        self.label_kpi_surgery.setGeometry(QtCore.QRect(110, 200, 101, 31))
        self.label_kpi_surgery.setObjectName("label_kpi_surgery")
        self.label_kpi_rev = QtWidgets.QLabel(self.tab_kpi)
        self.label_kpi_rev.setGeometry(QtCore.QRect(110, 340, 51, 21))
        self.label_kpi_rev.setObjectName("label_kpi_rev")
        self.line_2 = QtWidgets.QFrame(self.tab_kpi)
        self.line_2.setGeometry(QtCore.QRect(510, 0, 16, 681))
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_kpi_title_register = QtWidgets.QLabel(self.tab_kpi)
        self.lineEdit_kpi_title_register.setGeometry(QtCore.QRect(130, 60, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(38)
        self.lineEdit_kpi_title_register.setFont(font)
        self.lineEdit_kpi_title_register.setObjectName("lineEdit_kpi_title_register")
        self.lineEdit_kpi_title_search = QtWidgets.QLabel(self.tab_kpi)
        self.lineEdit_kpi_title_search.setGeometry(QtCore.QRect(710, 60, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(38)
        self.lineEdit_kpi_title_search.setFont(font)
        self.lineEdit_kpi_title_search.setObjectName("lineEdit_kpi_title_search")
        self.comboBox_kpi_month = QtWidgets.QComboBox(self.tab_kpi)
        self.comboBox_kpi_month.setGeometry(QtCore.QRect(700, 190, 91, 31))
        self.comboBox_kpi_month.setObjectName("comboBox_kpi_month")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_month.addItem("")
        self.comboBox_kpi_year = QtWidgets.QComboBox(self.tab_kpi)
        self.comboBox_kpi_year.setGeometry(QtCore.QRect(810, 190, 71, 31))
        self.comboBox_kpi_year.setObjectName("comboBox_kpi_year")
        self.comboBox_kpi_year.addItem("")
        self.comboBox_kpi_year.addItem("")
        self.comboBox_kpi_year.addItem("")
        self.pushButton_kpi_open = QtWidgets.QPushButton(self.tab_kpi)
        self.pushButton_kpi_open.setGeometry(QtCore.QRect(700, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_kpi_open.setFont(font)
        self.pushButton_kpi_open.setObjectName("pushButton_kpi_open")
        self.label_kpi_qc = QtWidgets.QLabel(self.tab_kpi)
        self.label_kpi_qc.setGeometry(QtCore.QRect(110, 310, 51, 21))
        self.label_kpi_qc.setObjectName("label_kpi_qc")
        self.comboBox_kpi_qc = QtWidgets.QComboBox(self.tab_kpi)
        self.comboBox_kpi_qc.setGeometry(QtCore.QRect(200, 310, 61, 21))
        self.comboBox_kpi_qc.setObjectName("comboBox_kpi_qc")
        self.comboBox_kpi_qc.addItem("")
        self.comboBox_kpi_qc.addItem("")
    
        self.label_kpi_modality = QtWidgets.QLabel(self.tab_kpi)
        self.label_kpi_modality.setGeometry(QtCore.QRect(110, 280, 70, 21))
        self.label_kpi_modality.setObjectName("label_kpi_modality")
        self.comboBox_kpi_modality = QtWidgets.QComboBox(self.tab_kpi)
        self.comboBox_kpi_modality.setGeometry(QtCore.QRect(200, 280, 61, 21))
        self.comboBox_kpi_modality.setObjectName("comboBox_kpi_modality")
        self.comboBox_kpi_modality.addItem("")
        self.comboBox_kpi_modality.addItem("")
        self.comboBox_kpi_modality.addItem("")

        self.label_kpi_comments = QtWidgets.QLabel(self.tab_kpi)
        self.label_kpi_comments.setGeometry(QtCore.QRect(110, 430, 81, 21))
        self.label_kpi_comments.setObjectName("label_kpi_comments")
        self.textEdit_kpi_comments = QtWidgets.QTextEdit(self.tab_kpi)
        self.textEdit_kpi_comments.setGeometry(QtCore.QRect(110, 460, 231, 131))
        self.textEdit_kpi_comments.setObjectName("textEdit_kpi_comments")
        MainWidget.addTab(self.tab_kpi, "")
        
        segmentationfunc.text_reader('/segmentation/stlnames.txt', self.textEdit_segmentation_image)
        designfunc.text_reader('/design/regular_names.txt',self.textEdit_design_image)
        reportfunc.text_reader('/report/standard_comments.txt', self.textEdit_report_image)
        
        self.retranslateUi(MainWidget)
        MainWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        """Manage the text of each item inside the UI"""

        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "CEToolkit"))
        self.label_stopwatch_title_stopwatch.setText(_translate("MainWidget", "StopWatch"))
        self.lineEdit_stopwatch_hour.setText(_translate("MainWidget", "00"))
        self.lineEdit_stopwatch_minutes.setText(_translate("MainWidget", "00"))
        self.lineEdit_stopwatch_seconds.setText(_translate("MainWidget", "00"))
        self.label_stopwatch_dot.setText(_translate("MainWidget", ":"))
        self.label_stopwatch_dot_2.setText(_translate("MainWidget", ":"))
        self.pushButton_stopwatch_reset.setText(_translate("MainWidget", "Reset"))
        self.pushButton_stopwatch_stop_up.setText(_translate("MainWidget", "Stop"))
        self.pushButton_stopwatch_start_up.setText(_translate("MainWidget", "StartUp"))
        self.pushButton_stopwatch_start_down.setText(_translate("MainWidget", "StartDown"))
        self.comboBox_stopwatch_targets.setItemText(0, _translate("MainWidget", "Targets"))
        self.comboBox_stopwatch_targets.setItemText(1, _translate("MainWidget", "Segmentation CT"))
        self.comboBox_stopwatch_targets.setItemText(2, _translate("MainWidget", "Segmentation CBCT"))
        self.comboBox_stopwatch_targets.setItemText(3, _translate("MainWidget", "Segmentation QC"))
        self.comboBox_stopwatch_targets.setItemText(4, _translate("MainWidget", "Technical QC"))
        self.comboBox_stopwatch_targets.setItemText(5, _translate("MainWidget", "Plastic Design"))
        self.comboBox_stopwatch_targets.setItemText(6, _translate("MainWidget", "Plastic Design Complex"))
        self.label_stopwatch_title_calculator.setText(_translate("MainWidget", "Time Calculator"))
        self.label_stopwatch_start.setText(_translate("MainWidget", "Start:"))
        self.label_stopwatch_end.setText(_translate("MainWidget", "End:"))
        self.dateTimeEdit_stopwatch_end.setDisplayFormat(_translate("MainWidget", " hh:mm "))
        self.dateTimeEdit_stopwatch_start.setDisplayFormat(_translate("MainWidget", " hh:mm"))
        self.label_stopwatch_adjustment.setText(_translate("MainWidget", "Adjustment:"))
        self.label_stopwatch_total.setText(_translate("MainWidget", "Total:"))
        self.pushButton_stopwatch_calculate.setText(_translate("MainWidget", "Calculate"))
        MainWidget.setTabText(MainWidget.indexOf(self.tab_stopwatch), _translate("MainWidget", "StopWatch"))
        self.comboBox_segmentation_surgery.setItemText(0, _translate("MainWidget", "Orthognatic"))
        self.comboBox_segmentation_surgery.setItemText(1, _translate("MainWidget", "Grafts"))
        self.comboBox_segmentation_surgery.setItemText(2, _translate("MainWidget", "Mandible Reconstruction"))
        self.comboBox_segmentation_surgery.setItemText(3, _translate("MainWidget", "MidFace Reconstruction"))
        self.comboBox_segmentation_surgery.setItemText(4, _translate("MainWidget", "PSI"))
        self.comboBox_segmentation_surgery.setItemText(5, _translate("MainWidget", "Craniofacial distraction"))
        self.comboBox_segmentation_surgery.setItemText(6, _translate("MainWidget", "Cranial vault reconstruction"))
        self.comboBox_segmentation_surgery.setItemText(7, _translate("MainWidget", "Midface aesthetic"))
        self.pushButton_segmentation_back.setText(_translate("MainWidget", "Back"))
        self.pushButton_segmentation_next.setText(_translate("MainWidget", "Next"))
        self.pushButton_segmentation_names.setText(_translate("MainWidget", "Names"))
        self.pushButton_segmentation_framework.setText(_translate("MainWidget", "FrameWork"))
        self.pushButton_segmentation_objects.setText(_translate("MainWidget", "Objects"))
        self.pushButton_segmentation_preplanfolders.setText(_translate("MainWidget", "Preplaning Folders"))
        self.pushButton_segmentation_preplancuts.setText(_translate("MainWidget", "Preplanning cuts"))
        MainWidget.setTabText(MainWidget.indexOf(self.tab_segmentation), _translate("MainWidget", "Segmentation"))
        self.pushButton_design_next.setText(_translate("MainWidget", "Next"))
        self.pushButton_design_back.setText(_translate("MainWidget", "Back"))
        self.pushButton_design_rnames.setText(_translate("MainWidget", "Regular Names"))
        self.pushButton_design_pnames.setText(_translate("MainWidget", "Production Names"))
        self.pushButton_design_parameters.setText(_translate("MainWidget", "Parameters"))
        self.pushButton_design_wraps.setText(_translate("MainWidget", "Wraps"))
        self.pushButton_design_folder.setText(_translate("MainWidget", "Folder"))
        self.pushButton_design_ceph.setText(_translate("MainWidget", "Cephalometry"))
        self.pushButton_design_flags.setText(_translate("MainWidget", "Post-Processing flags"))
        MainWidget.setTabText(MainWidget.indexOf(self.tab_design), _translate("MainWidget", "Design"))
        self.pushButton_report_next.setText(_translate("MainWidget", "Next"))
        self.pushButton_report_back.setText(_translate("MainWidget", "Back"))
        self.pushButton_report_comments.setText(_translate("MainWidget", "Standard Comments"))
        self.pushButton_report_parameters.setText(_translate("MainWidget", "Parameters"))
        self.pushButton_report_teeth.setText(_translate("MainWidget", "Teeth numeration"))
        self.pushButton_report_colors.setText(_translate("MainWidget", "Colors"))
        self.pushButton_report_ART.setText(_translate("MainWidget", "ART"))
        MainWidget.setTabText(MainWidget.indexOf(self.tab_report), _translate("MainWidget", "Report"))
        self.lineEdit_kpi_caseid.setPlaceholderText(_translate("MainWidget", "Case ID"))
        self.lineEdit_kpi_time.setPlaceholderText(_translate("MainWidget", "Time"))
        self.comboBox_kpi_surgery.setItemText(0, _translate("MainWidget", "Seg Orthognatic"))
        self.comboBox_kpi_surgery.setItemText(1, _translate("MainWidget", "Seg Reconstruction"))
        self.comboBox_kpi_surgery.setItemText(2, _translate("MainWidget", "Seg PSI/MOD/POSTOP"))
        self.comboBox_kpi_surgery.setItemText(3, _translate("MainWidget", "Seg Other"))
        self.comboBox_kpi_surgery.setItemText(4, _translate("MainWidget", "Des Orthognatic"))
        self.comboBox_kpi_surgery.setItemText(5, _translate("MainWidget", "Des Reconstruction"))
        self.comboBox_kpi_surgery.setItemText(6, _translate("MainWidget", "Des PSI"))
        self.comboBox_kpi_surgery.setItemText(7, _translate("MainWidget", "Des Other"))
        self.comboBox_kpi_rev.setItemText(0, _translate("MainWidget", "YES"))
        self.comboBox_kpi_rev.setItemText(1, _translate("MainWidget", "NO"))
        self.comboBox_kpi_rev.setItemText(2, _translate("MainWidget", "N/A"))
        self.pushButton_kpi_register.setText(_translate("MainWidget", "Register"))
        self.label_kpi_surgery.setText(_translate("MainWidget", "Surgery:"))
        self.label_kpi_rev.setText(_translate("MainWidget", "REV0:"))
        self.lineEdit_kpi_title_register.setText(_translate("MainWidget", "Register"))
        self.lineEdit_kpi_title_search.setText(_translate("MainWidget", "Search"))
        self.comboBox_kpi_month.setItemText(0, _translate("MainWidget", "01"))
        self.comboBox_kpi_month.setItemText(1, _translate("MainWidget", "02"))
        self.comboBox_kpi_month.setItemText(2, _translate("MainWidget", "03"))
        self.comboBox_kpi_month.setItemText(3, _translate("MainWidget", "04"))
        self.comboBox_kpi_month.setItemText(4, _translate("MainWidget", "05"))
        self.comboBox_kpi_month.setItemText(5, _translate("MainWidget", "06"))
        self.comboBox_kpi_month.setItemText(6, _translate("MainWidget", "07"))
        self.comboBox_kpi_month.setItemText(7, _translate("MainWidget", "08"))
        self.comboBox_kpi_month.setItemText(8, _translate("MainWidget", "09"))
        self.comboBox_kpi_month.setItemText(9, _translate("MainWidget", "10"))
        self.comboBox_kpi_month.setItemText(10, _translate("MainWidget", "11"))
        self.comboBox_kpi_month.setItemText(11, _translate("MainWidget", "12"))
        self.comboBox_kpi_year.setItemText(0, _translate("MainWidget", "2020"))
        self.comboBox_kpi_year.setItemText(1, _translate("MainWidget", "2021"))
        self.comboBox_kpi_year.setItemText(2, _translate("MainWidget", "2022"))
        self.pushButton_kpi_open.setText(_translate("MainWidget", "Open file"))
        self.label_kpi_qc.setText(_translate("MainWidget", "QC:"))
        self.comboBox_kpi_qc.setItemText(0, _translate("MainWidget", "YES"))
        self.comboBox_kpi_qc.setItemText(1, _translate("MainWidget", "NO"))

        self.label_kpi_modality.setText(_translate("MainWidget", "Modality:"))
        self.comboBox_kpi_modality.setItemText(0, _translate("MainWidget", "CT"))
        self.comboBox_kpi_modality.setItemText(1, _translate("MainWidget", "CBCT"))
        self.comboBox_kpi_modality.setItemText(2, _translate("MainWidget", "N/A"))

        self.label_kpi_comments.setText(_translate("MainWidget", "Comments:"))
        MainWidget.setTabText(MainWidget.indexOf(self.tab_kpi), _translate("MainWidget", "KPI"))

#Connections#

#STOPWATCH#

        self.pushButton_stopwatch_start_up.clicked.connect(self.start_stopwatch_up)
        self.pushButton_stopwatch_stop_up.clicked.connect(self.stop_stopwatch_up)
        self.pushButton_stopwatch_reset.clicked.connect(self.stop_stopwatch_reset)
        self.pushButton_stopwatch_start_down.clicked.connect(self.start_stopwatch_down)

        self.comboBox_stopwatch_targets.currentIndexChanged.connect(stopwatchfunc.comboBox_stopwatch_targets_change)

        self.pushButton_stopwatch_calculate.clicked.connect(stopwatchfunc.calculate_diff)

#Segmentation#

        self.pushButton_segmentation_names.clicked.connect(segmentationfunc.names_button)
        self.pushButton_segmentation_framework.clicked.connect(segmentationfunc.framework_button)
        self.pushButton_segmentation_objects.clicked.connect(segmentationfunc.objects_button)
        self.pushButton_segmentation_preplanfolders.clicked.connect(segmentationfunc.preplanning_folder_button)
        self.pushButton_segmentation_preplancuts.clicked.connect(segmentationfunc.preplanning_cuts_button)

        self.pushButton_segmentation_next.clicked.connect(segmentationfunc.next)
        self.pushButton_segmentation_back.clicked.connect(segmentationfunc.back)

        self.comboBox_segmentation_surgery.currentIndexChanged.connect(segmentationfunc.combobox_change)

#Design#

        self.pushButton_design_rnames.clicked.connect(designfunc.rnames_button)
        self.pushButton_design_pnames.clicked.connect(designfunc.pnames_button)
        self.pushButton_design_parameters.clicked.connect(designfunc.parameters_button)
        self.pushButton_design_wraps.clicked.connect(designfunc.wraps_button)
        self.pushButton_design_folder.clicked.connect(designfunc.folder_button)
        self.pushButton_design_ceph.clicked.connect(designfunc.ceph_button)
        self.pushButton_design_flags.clicked.connect(designfunc.flags_button)

        self.pushButton_design_next.clicked.connect(designfunc.next)
        self.pushButton_design_back.clicked.connect(designfunc.back)

#Report#

        self.pushButton_report_comments.clicked.connect(reportfunc.comments_button)
        self.pushButton_report_parameters.clicked.connect(reportfunc.parameters_button)
        self.pushButton_report_teeth.clicked.connect(reportfunc.teeth_button)
        self.pushButton_report_colors.clicked.connect(reportfunc.colors_button)
        self.pushButton_report_ART.clicked.connect(reportfunc.art_button)

        self.pushButton_report_next.clicked.connect(reportfunc.next)
        self.pushButton_report_back.clicked.connect(reportfunc.back)
        self.comboBox_kpi_surgery.currentText

#KPI
        self.pushButton_kpi_register.clicked.connect(kpifunc.register_button)
        self.pushButton_kpi_open.clicked.connect(kpifunc.openkpi_button)

#Timer Funcitions#
#STOPWATCH

    def start_stopwatch_up(self):
        """Initialize the timer by 1 seg per second"""

        self.func_timer(self.clock_up)
        
    def stop_stopwatch_up(self):
        """Stop the timer"""

        try:
            self.timer.stop()
            stopwatchfunc.stop_time()
        except AttributeError:
            pass

    def stop_stopwatch_reset(self):  
        """reset the stopwatch 00:00:00"""

        try:
            self.timer.stop()
            stopwatchfunc.reset_time()
            
        except(AttributeError):
            pass

    def start_stopwatch_down(self):
        """take the line edit values an initialize the timer"""

        try:
            second = int(self.lineEdit_stopwatch_seconds.text())
            minute = int(self.lineEdit_stopwatch_minutes.text())
            hour = int(self.lineEdit_stopwatch_hour.text())
            if second == 0 and minute == 0 and hour == 0:
                return
            stopwatchfunc.set_countdown_values(hour,minute,second)
            self.func_timer(self.downclock)
            
        except(ValueError):
            stopwatchfunc.error_message("Please input numbers")

    def clock_up(self):
        """Call the logic of sum clock in the functions file"""    

        stopwatchfunc.calculate_time_up()

    def downclock(self):
        """Call the logic of substraction clock in the functions file"""

        stopwatchfunc.calculate_time_down()

    def func_timer(self,timer):
        """Initialize any timer calling the correct logic"""
        
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(timer)
        self.timer.start(1000)

if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    app_icon = QIcon("./media/img/materialise_logo_zki_icon.ico")
    app.setWindowIcon(app_icon)
    MainWidget = QtWidgets.QTabWidget()
    ui = Ui_MainWidget()
    ui.setupUi(MainWidget)
    MainWidget.show()
    sys.exit(app.exec_())